### ISSUE TITLE
Paclet Server Integration

### ISSUE THREAD

**Issue by b3m2a1** [Dih5/ErrorPlot#1]
I was wondering if you'd want to add your package to the [Paclet Server / Package Repo)](https://paclets.github.io/PacletServer/) I've set up for the general Mathematica community. Per [this](https://github.com/paclets/PacletServer/issues/35) I'm trying to increase awareness and get more paclets on the server so that more people can benefit from it.

I can handle any initial reformatting necessary to make everything work right, and I'll submit a pull request with any changes.

**Comment by Dih5** [comment]
I like the Paclet server idea. Please, feel free to do so.

**Comment by Dih5** [comment]
Merged #2.
Please, leave a message when its working, so I can try it and update the readme.

**Comment by b3m2a1** [comment]
It's [on the server](https://paclets.github.io/PacletServer/errorplot.html). When you have updates, simply open an issue on the server's GitHub page (look at some of the closed ones to see what Szabolcs has done).

**Comment by Dih5** [comment]
Thank you for work, I hope to see the server grow.
